import { ThemeProvider } from "@mui/material";
import { muiTheme } from "..";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={muiTheme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
